ParentManagementGroup    = "tsnp-landingzones-corp"
subscription_dmz         = "73330a6e-7a8f-4e88-8727-d80940161c35"
subscription_private     = "584c195a-d2fb-4c33-a0e4-c9dce17f2ff6"
RMISdmz_Name             = "RMISDMZ"
RMISdmz_id               = "tsnp-landingzones-np-RMISdmz"
RMISprivate_Name         = "RMISPrivate"
RMISprivate_id           = "tsnp-landingzones-np-RMISprivate"
statename                = "tfstate"